### ISSUE TITLE
Allow compensation for monitor frame width.

### ISSUE THREAD

**Issue by josefdlange** [tomtaylor/satellite-eyes#45]
My monitors have about a 1.5cm frame around them and as such when viewing the (gorgeous!) map stretched across my screen, things don't line up quite right, since the app doesn't handle the "lost space" between displays. It would be great if we could have some sort of slider/dial to "overscan" the image on each display by a slightly variable amount. For my screens (1080p) I'd imagine this range could live between 0 and 200px, maybe even 0-100px.

**Comment by tomtaylor** [comment]
Happy to accept a patch for this if you're able, but I probably won't implement it myself.

**Comment by josefdlange** [comment]
I had forgotten about this! I'll take a look in a free cycle.
