### ISSUE TITLE
Satellite Eyes forcing constant graphics mode switching

### ISSUE THREAD

**Issue by arigesher** [tomtaylor/satellite-eyes#48]
When I run Satellite Eyes, I get big CPU spikes in a sawtooth pattern unless I turn off the graphics switching capability under Energy Saver preferences. My logs get spammed with this, over and over, and the system becomes somewhat sluggish:

```
6/2/15 1:12:21.296 PM WindowServer[186]: Received display connect changed for display 0x4280382
6/2/15 1:12:21.320 PM WindowServer[186]: Found 27 modes for display 0x04280382 [27, 0]
6/2/15 1:12:21.351 PM WindowServer[186]: CGXMuxAcknowledge: Posting glitchless acknowledge
6/2/15 1:12:21.383 PM WindowServer[186]: Received display connect changed for display 0x4280382
6/2/15 1:12:21.383 PM WindowServer[186]: Found 1 modes for display 0x04280382 [1, 0]
6/2/15 1:12:21.384 PM WindowServer[186]: Received display connect changed for display 0x3f003f
6/2/15 1:12:21.384 PM WindowServer[186]: Found 1 modes for display 0x003f003f [1, 0]
6/2/15 1:12:21.384 PM WindowServer[186]: Received display connect changed for display 0x3f0040
6/2/15 1:12:21.384 PM WindowServer[186]: Found 1 modes for display 0x003f0040 [1, 0]
6/2/15 1:12:21.384 PM WindowServer[186]: Received display connect changed for display 0x3f0041
6/2/15 1:12:21.385 PM WindowServer[186]: Found 1 modes for display 0x003f0041 [1, 0]
6/2/15 1:12:21.605 PM WindowServer[186]: MPAccessSurfaceForDisplayDevice: Set up page flip mode on display 0x04280382 device: 0x7f8130406540  isBackBuffered: 1 numComp: 3 numDisp: 3
6/2/15 1:12:21.917 PM Satellite Eyes[7644]: Looking up file at: /Users/regs/Library/Application Support/Satellite Eyes/map-f58e9749db158b448f167729b3bdd5c6.png
6/2/15 1:12:21.917 PM Satellite Eyes[7644]: Map image already cached: /Users/regs/Library/Application Support/Satellite Eyes/map-f58e9749db158b448f167729b3bdd5c6.png
6/2/15 1:12:23.978 PM WindowServer[186]: Received display connect changed for display 0x4280382
6/2/15 1:12:23.994 PM WindowServer[186]: Found 27 modes for display 0x04280382 [27, 0]
6/2/15 1:12:24.026 PM WindowServer[186]: Received display connect changed for display 0x3f003f
6/2/15 1:12:24.026 PM WindowServer[186]: Found 1 modes for display 0x003f003f [1, 0]
6/2/15 1:12:24.026 PM WindowServer[186]: Received display connect changed for display 0x3f0040
6/2/15 1:12:24.027 PM WindowServer[186]: Found 1 modes for display 0x003f0040 [1, 0]
6/2/15 1:12:24.027 PM WindowServer[186]: Received display connect changed for display 0x3f0041
6/2/15 1:12:24.027 PM WindowServer[186]: Found 1 modes for display 0x003f0041 [1, 0]
6/2/15 1:12:24.029 PM WindowServer[186]: CGXMuxAcknowledge: Posting glitchless acknowledge
6/2/15 1:12:24.036 PM WindowServer[186]: MPAccessSurfaceForDisplayDevice: Set up page flip mode on display 0x04280382 device: 0x7f8130406540  isBackBuffered: 1 numComp: 3 numDisp: 3
6/2/15 1:12:24.104 PM WindowServer[186]: Received display connect changed for display 0x4280382
6/2/15 1:12:24.104 PM WindowServer[186]: Found 1 modes for display 0x04280382 [1, 0]
6/2/15 1:12:24.699 PM Satellite Eyes[7644]: Looking up file at: /Users/regs/Library/Application Support/Satellite Eyes/map-f58e9749db158b448f167729b3bdd5c6.png
6/2/15 1:12:24.699 PM Satellite Eyes[7644]: Map image already cached: /Users/regs/Library/Application Support/Satellite Eyes/map-f58e9749db158b448f167729b3bdd5c6.png
```

Exiting Satellite Eyes makes this behavior stop.  Starting it up makes it start again.

Hardware Overview:

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro10,1
  Processor Name:   Intel Core i7
  Processor Speed:  2.3 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB
  Boot ROM Version: MBP101.00EE.B07

System Software Overview:

  System Version:   OS X 10.10.3 (14D136)
  Kernel Version:   Darwin 14.3.0
  Boot Volume:  Macintosh HD
  Boot Mode:    Normal
  Secure Virtual Memory:    Enabled
  Time since boot:  14:03

**Comment by tdsmith** [comment]
I noticed the same thing today. My screen flickers when the GPU switches from high-performance to integrated, too.

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP114.0172.B00
  SMC Version (system):	2.30f1

System Software Overview:

  System Version:	OS X 10.10.3 (14D2134)
  Kernel Version:	Darwin 14.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  Time since boot:	6 minutes

**Comment by tomtaylor** [comment]
That's odd. I'm afraid I don't have a MacBook Pro with a discrete GPU to test it with. Are either of you able to toggle `NSSupportsAutomaticGraphicsSwitching` to off in the .plist file, and try it again?

**Comment by tdsmith** [comment]
Changing that key in Satellite Eyes.app/Contents/Info.plist with `plutil -replace NSSupportsAutomaticGraphicsSwitching -bool false Info.plist`had no effect for me.

**Comment by tdsmith** [comment]
It's also very enthusiastic about refreshing the map even though I'm not moving! It seems to be refreshing about every 15 seconds, which why this is surfacing as a problem for me.

**Comment by tomtaylor** [comment]
Following up here to say: if anyone has a MBP with a discrete GPU and can help tracking this down, please get in touch.

**Comment by tomtaylor** [comment]
Closing this for now.
