### ISSUE TITLE
Maps at wrong locations at different zoom level

### ISSUE THREAD

**Issue by robertsky** [tomtaylor/satellite-eyes#50]
The map returns at different locations at different zoom levels. For the neighbourhood level, it is more or less right at Singapore:
<img width="1270" alt="screen shot 2015-10-01 at 5 06 14 pm" src="https://cloud.githubusercontent.com/assets/1820367/10216874/d01063ae-685e-11e5-981e-9bb66c757957.png">
However, the next two zoom levels, at city and region levels, they return somewhere north of Singapore, in Malaysia, or even in the Straits of Malacca:
<img width="1264" alt="screen shot 2015-10-01 at 5 06 24 pm" src="https://cloud.githubusercontent.com/assets/1820367/10216875/d036a140-685e-11e5-91b5-ed0597545417.png">
<img width="1265" alt="screen shot 2015-10-01 at 5 06 36 pm" src="https://cloud.githubusercontent.com/assets/1820367/10216876/d03b51f4-685e-11e5-8ea2-d7ed634e473d.png">

**Comment by tomtaylor** [comment]
I've not seen this before - are you using multiple monitors?

**Comment by tomtaylor** [comment]
Closing this, but feel free to reopen with more info.

**Comment by robertsky** [comment]
Apologies for the delay. Yes, I am using multiple monitors.
