### ISSUE TITLE
El Capitan "problem updating the map"

### ISSUE THREAD

**Issue by registered99** [tomtaylor/satellite-eyes#53]
I get this error on first launch. I ensured that location privileges were granted. 

Is there something I'm maybe doing wrong?

**Comment by tomtaylor** [comment]
It sounds like there might have been a network issue between you and the map tile server. I don't think there are any particular compatibility issues with El Capitan. I know the error messages could do with some work.

**Comment by registered99** [comment]
Yep, I think you're right. On a different network on a different day, it works for me. Thanks!

**Comment by tomtaylor** [comment]
Phew!
