### ISSUE TITLE
Added New Styles to Map-Styles-Manager

### ISSUE THREAD

**Issue by jwgoldsmith** [tomtaylor/satellite-eyes#54]
@tomtaylor 
If you want additional map styes, here are the tile-sets I've added to my personal map-style manager. 

**MapBox SpaceStation** 
`https://a.tiles.mapbox.com/v4/katydecorah.027b9d3f/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoia2F0eWRlY29yYWgiLCJhIjoiNGxUd0FiRSJ9.W6JiC41LhSNbMQjuF3NGhA`

**MapBox SuperMario**
`https://b.tiles.mapbox.com/v4/duncangraham.552f58b0/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZHVuY2FuZ3JhaGFtIiwiYSI6IlJJcWdFczQifQ.9HUpTV1es8IjaGAf_s64VQ`

**MapBox Camouflage**
`https://api.mapbox.com/styles/v1/edenhalperin/cifq0r0e5000q85m0d293k6mq/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZWRlbmhhbHBlcmluIiwiYSI6IlFRZG0zMWMifQ.QUNKx4tIMjZfwmrE8SE6Bg`

**MapBox Standard**
`https://api.mapbox.com/styles/v1/saman/cif61g3y602sju1m5b02255c9/tiles/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww`

**MapBox X-ray**
`https://api.mapbox.com/styles/v1/tatiana/cigv33jhr000i9kkk9puogrpy/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoidGF0aWFuYSIsImEiOiJjaWxzMnR6N20wOHMxdWhtMXdjdXlwdjNrIn0.u405gXn3WikWtJAiiIlmkw`

**MapBox Vintage**
`https://api.mapbox.com/styles/v1/mslee/cif5p01n202nisaktvljx9mv3/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg`

**MapBox SwissSki**
`https://api.mapbox.com/styles/v1/mslee/cij1zoclj002y8rkkdjl69psd/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg`

**MapBox Santiago**
`https://api.mapbox.com/styles/v1/angelde/ciit3wq5300q3c8lz2uhd8bq7/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYW5nZWxkZSIsImEiOiI2RlppLW1VIn0.0PdqJ6CFs0V-cexQY0KT3w`

**MapBox Runner**
`https://api.mapbox.com/styles/v1/grafa/587d7dc0/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZ3JhZmEiLCJhIjoiZjk3Mjk2YWYzZTNlYjM3ODdlNzJlOWJlM2VjZGI0ZDEifQ.OTT9oT7CqAc9vZsnJLT51Q`

**MapBox Winter Wonderland**
`https://a.tiles.mapbox.com/v4/andreasviglakis.76e0cee7/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoidG1jdyIsImEiOiJIZmRUQjRBIn0.lRARalfaGHnPdRcc-7QZYQ`

**Ancona Blueprinted**
`http://b.tiles.mapbox.com/v4/laurenancona.lgh0leco/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibGF1cmVuYW5jb25hIiwiYSI6Im5EaldBcVUifQ.MTeXi8ZLmYhMBxnZ0nBG3A`

**Financial Times**
`https://b.tiles.mapbox.com/v3/financialtimes.map-w7l4lfi8/{z}/{x}/{y}.png`

**Kowalsky Lichtenstein**
`https://a.tiles.mapbox.com/v4/katiekowalsky.236692c1/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoia2F0aWVrb3dhbHNreSIsImEiOiJHR2hfdlBNIn0.GUMLsSnT-SYx4ew7b77kqw`

**Comment by bobthecow** [comment]
sweet!

**Comment by jwgoldsmith** [comment]
Thanks @bobthecow. Here are another 11 I've added since last week.

**Foursquare**
`http://b.tiles.mapbox.com/v4/foursquare.kndk7qfr/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**MapBox Dark**
`http://b.tiles.mapbox.com/v4/bobbysud.lff1p11d/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**MapBox Wheatgrass**
`http://a.tiles.mapbox.com/v4/bobbysud.lff263ph/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**Saman (MapBox) Randomness**
`https://a.tiles.mapbox.com/v3/saman.h6ek9086/{z}/{x}/{y}.png`

**Strava Terrain**
`http://c.tiles.mapbox.com/v4/strava.j80kjk5o/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic3RyYXZhIiwiYSI6IlpoeXU2U0UifQ.c7yhlZevNRFCqHYm6G6Cyg`

**Strava Streets**
`http://c.tiles.mapbox.com/v4/strava.blprdx6r/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic3RyYXZhIiwiYSI6IlpoeXU2U0UifQ.c7yhlZevNRFCqHYm6G6Cyg`

**MapBox Roy**
`http://b.tiles.mapbox.com/v4/bobbysud.lff1o1c6/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**MapBox White**
`http://b.tiles.mapbox.com/v4/bobbysud.lff26ajh/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**MapBox ???** (I don't know what to call this tile set)
`https://a.tiles.mapbox.com/v4/saman.ed44282c/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww`

**MapBox ????** (again...)
`http://b.tiles.mapbox.com/v4/bobbysud.e67f128a/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYm9iYnlzdWQiLCJhIjoiTi16MElIUSJ9.Clrqck--7WmHeqqvtFdYig`

**Comment by tomtaylor** [comment]
Thanks, this looks great, but some of these maps are styles specific to the owner, and I'm not sure I can include them in the app. If you can you clarify the source, copyright and attribution requirements for each, I can try and include.

**Comment by tomtaylor** [comment]
@jwgoldsmith going to close this, but happy to open again if you can get the attribution details.
