### ISSUE TITLE
Attribution in Manage Map Styles

### ISSUE THREAD

**Issue by jqnatividad** [tomtaylor/satellite-eyes#56]
It would be nice and respectful (and only proper since it's in the tile provider's TOSes) that we have a field to specify an attribution string for each Map Style.

The attribution, ideally, should be discretely displayed at the lower right hand side of the wallpaper.

**Comment by tomtaylor** [comment]
There is a logo field, used for Bing Maps, specifically to comply with their terms. Other maps are credited in the 'About' window. If you feel that's not suitable, please let me know.
