### ISSUE TITLE
API Key required for Thunderforest maps 

### ISSUE THREAD

**Issue by aslakr** [tomtaylor/satellite-eyes#58]
(Version 1.4.1/Build 1112)

It seems like the Thunderforest maps (OCM, Transport, Landscape and Outdoors) require an API Key

![api key required for thunderforest ocm](https://cloud.githubusercontent.com/assets/80737/23404969/1936c330-fdb8-11e6-9b04-ce8fcdb80cf4.png)

**Comment by tomtaylor** [comment]
Thanks for reporting this. I'll see if it's possible to get an API key for Thunderforest and ship an update, or remove them from the application.

**Comment by tomtaylor** [comment]
Fixed in 1.4.2.
