### ISSUE TITLE
Can't install pods

### ISSUE THREAD

**Issue by ralcr** [tomtaylor/satellite-eyes#60]
i have the newest cocoapods and i get this when trying to install

Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] The dependency `Reachability (~> 3.1.0)` is not used in any concrete target.
The dependency `CocoaLumberjack (~> 1.9.1)` is not used in any concrete target.
The dependency `AFNetworking (~> 1.3)` is not used in any concrete target.
The dependency `Sparkle (~> 1.8.0)` is not used in any concrete target.

**Comment by lamelas** [comment]
Try something like this in your Podfile:

    target 'Satellite Eyes' do
        pod 'Reachability',  '~> 3.1.0'
        pod 'CocoaLumberjack', '~> 1.9.1'
        pod 'AFNetworking', '~> 1.3'
        pod 'Sparkle', '~> 1.17'
    end

**Comment by tomtaylor** [comment]
Work in #61 underway on this.

**Comment by tomtaylor** [comment]
Fixed in master.
