### ISSUE TITLE
Issue with multiple monitors under High Sierra

### ISSUE THREAD

**Issue by 2bithacker** [tomtaylor/satellite-eyes#65]
Since upgrading to High Sierra, I've been having an issue where the wallpaper on one of my monitors doesn't center properly, but only when switching from my laptop's screen to the two external monitors. If I start the Mac with both external monitors connected, the wallpaper is fine until undocking/redocking.

The arrangement of my screens:
![screen shot 2018-01-04 at 16 20 26](https://user-images.githubusercontent.com/1847654/34573135-369da838-f16b-11e7-8921-79150eb7687f.png)

The portrait monitor works fine:
![screen shot 2018-01-04 at 16 16 38 2](https://user-images.githubusercontent.com/1847654/34573159-46feed18-f16b-11e7-8701-b61a515b955a.png)

But the landscape (primary?) monitor does this:
![screen shot 2018-01-04 at 16 16 38](https://user-images.githubusercontent.com/1847654/34573190-56bee898-f16b-11e7-8bd1-8c0fdcbabab3.png)

I figured it was an issue with how Satellite Eyes is composing the image, since the bing logo in the lower right corner is in the right place.

**Comment by tomtaylor** [comment]
I think you might have a badly cached set of tiles - can you try the 'refresh the map' button in the menu and see if it fixes itself?

**Comment by 2bithacker** [comment]
The problem isn't happening now, so that could have been it. I think I tried the refresh button when it was happening and it didn't have an effect, but I'll try it if the problem starts up again.

Thanks!
