### ISSUE TITLE
Issue with 4k Monitors when using the Halftone Dark Image Effect

### ISSUE THREAD

**Issue by tyleremiller** [tomtaylor/satellite-eyes#66]
Just picked up a BenQ PD3200U monitor and was tweaking out because there seemed to be some green banding, which was exacerbated when windows were moved around, but only with certain applications. This would cause the bands to move and dance around.

I can stop the issue by changing my image effect in Satellite Eyes from Halftone Dark to any other effect. I'm guessing it's an interpolation thing having to do with the size of the dots in Halftone Dark. The effects are visible if i take a screenshot and then view the screenshot at 100% size on the monitor, however the green banding disappears when zooming in on the image.

![screenshot 2018-01-08 17 46 33](https://user-images.githubusercontent.com/5598993/34701257-f96feaf0-f49b-11e7-8e83-cb0c489eb8bc.png)

**Comment by tomtaylor** [comment]
Sorry, I'm not sure what we can do about this. I think halftone effects cause havoc with some display drivers - a bit like moire. I'm afraid you'll just have to use a different effect.

**Comment by tyleremiller** [comment]
yep - Which is what i'm doing now. A potential solution might be to allow for the size/spacing of the halftone pattern to be manually adjusted as that would probably stop the effect?
