### ISSUE TITLE
Gibberish Permissions Window First Use

### ISSUE THREAD

**Issue by jessebett** [tomtaylor/satellite-eyes#67]
I get this message the first time I run the app:
`P≥‡™ˇ@ would like to use your current location.`
<img width="595" alt="screen shot 2018-04-13 at 3 54 18 pm" src="https://user-images.githubusercontent.com/4240549/38755269-1cc03136-3f33-11e8-93a4-fada08124ab6.png">

**Comment by tomtaylor** [comment]
That's very odd, I've not seen that before. Is your installation of MacOS using a non-English language?

**Comment by jessebett** [comment]
My preferred language in region settings is English (Canada).

(also thanks for this, it's really wonderful!)

**Comment by tomtaylor** [comment]
Hmm, I've got no idea what would cause this then! Did you use one of the downloaded builds from http://satelliteeyes.tomtaylor.co.uk or did you build it yourself?

**Comment by tomtaylor** [comment]
PS: thanks!

**Comment by jessebett** [comment]
I used the build downloaded from your site.

**Comment by tomtaylor** [comment]
I've not seen this anywhere else so I'm going to close for now and chalk it up to MacOS gremlins.
