### ISSUE TITLE
Stuck on 'Problem updating map'

### ISSUE THREAD

**Issue by NortonTech3D** [tomtaylor/satellite-eyes#80]
Hey everyone, I'm not very familiar with the inner workings of Satellite Eyes, but for a while now it has been telling me that there was a problem updating the map. If I click to open in browser I can pull up the map just fine, but the app never seems to update properly. Any ideas how I might troubleshoot this?

**Comment by jcottr** [comment]
I had the same issue with the Stamen maps, but was able to get it working by switching the map type to Bing Arial.

This may be related to https://github.com/tomtaylor/satellite-eyes/issues/76 (`Stamen Maps tiles moving to Stadia`). Though I haven't tested each map type to confirm the update issue is isolated to Stamen maps.

**Comment by NortonTech3D** [comment]
That's what it appears to be, sorry I meant to update this and forgot! I used my own API keys adn it works great now haha
